version: '3'

services:

  app:
    build:
      dockerfile: ./etc/docker/artifacts/Dockerfile.ci
      context: ../../../
    environment:
      - ELASTIC_HOST=elasticsearch:9200
      - POSTGRES_HOST=postgress

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    volumes:
      - "$PWD/etc/docker/dev/kibana/config:/usr/share/kibana/config/kibana.yml"

  postgress:
    image: postgres
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DATABASE: demo
